### ISSUE TITLE
[BUG] 启动客户端报错

### ISSUE THREAD

**Issue by Ycshell** [xieyumc/YuYuWechat#10]
# 提出issues前请先确保你看完了README

**描述Bug**  
清晰简洁地描述bug是什么。

**重现步骤**  
请描述你做了什么操作

**截图**  
![2024-08-21_15-57-](https://github.com/user-attachments/assets/cfa9e4dc-c238-4a81-8228-1a607dd58c07)。

**环境 (请完成以下信息):**
- OS: [e.g. windows11]
- 微信版本

**Comment by xieyumc** [comment]
你是用源码运行客户端的吗，试一下docker可以运行吗

我感觉是你的数据库没有配置好，请确保使用了postgresql并且端口号为5432，默认密码tykWyr-bepqu6-fafvym

如果不是为了开发，建议使用docker一键部署，问题会少很多

**Comment by Ycshell** [comment]
感谢。源码启动。postgresql的默认密码改成tykWyr-bepqu6-fafvym可以正常运行了

**Comment by Ycshell** [comment]
大佬。能在说明文档中。写下postgresql的默认密码改成tykWyr-bepqu6-fafvym。还有就是后台源码的admin账号密码多少啊

**Comment by xieyumc** [comment]
已更新文档，后台管理密码请你自己创建

python manage.py createsuperuser
