### ISSUE TITLE
程序无法启动问题

### ISSUE THREAD

**Issue by LXT2017** [xieyumc/YuYuWechat#11]
我微信安装在了其他路径，按照要求创建了C:\Program Files\Tencent\WeChat\WeChat.exe的快捷方式，然后服务器文件启动正常，但是http://127.0.0.1:8000/ 网站输入为404，但是使用ping时回复了pong，这是怎么回事？
![image](https://github.com/user-attachments/assets/8436daf2-d642-4108-962b-c94cfecb4151)

另外，我解压的客户端文件找不到可执行程序，是怎么回事？

最后期待您的回复

**Comment by xieyumc** [comment]
你好，你的服务端配置是正确的，服务端并没有管理网页，它只是接受客户端的http请求，然后进行自动化操作，所以访问http://127.0.0.1:8000/      会返回404

解压的客户端文件找不到可执行程序是因为客户端使用了许多组件，不好打包为exe，目前客户端支持docker部署和源码运行。

部署客户端请参考readme的第三节https://github.com/xieyumc/YuYuWechat?tab=readme-ov-file#3部署客户端
