### ISSUE TITLE
[BUG] win 11 系统 服务端发送信息失败

### ISSUE THREAD

**Issue by anbinzhang** [xieyumc/YuYuWechat#14]
请求这个接口 http://127.0.0.1:8000/wechat/check_wechat_status/

返回
{
    "status": "Error",
    "error": "[WinError 2] 系统找不到指定的文件。"
}
服务日志
[19/Sep/2024 13:39:16] "POST /wechat/send_message/ HTTP/1.1" 500 157
[19/Sep/2024 13:39:39] "POST /wechat/check_wechat_status HTTP/1.1" 301 0
[19/Sep/2024 13:39:39] "GET /wechat/check_wechat_status/ HTTP/1.1" 405 35
[19/Sep/2024 13:39:44] "POST /wechat/check_wechat_status/ HTTP/1.1" 500 111

**Comment by xieyumc** [comment]
你的微信是否安装在`C:/Program Files/Tencent/WeChat/WeChat.exe`

若不是，请放一个快捷方式在这里

**Comment by anbinzhang** [comment]
是安装在其他路径，这个路径也放快捷方式
![微信图片_20240919135752](https://github.com/user-attachments/assets/edd5baa1-a545-4d88-bf79-0efe08107294)

**Comment by xieyumc** [comment]
你试试微信直接安装在这个目录可以吗，因为我微信就默认安装在这里的，没测试快捷方式是否也可行

若直接安装可以，快捷方式不行，后续我考虑更新修复这个问题

**Comment by anbinzhang** [comment]
好的，谢谢

**Comment by anbinzhang** [comment]
这个路径能改吗；重新安装怕聊天记录丢失。

**Comment by xieyumc** [comment]
可以修改，`YuYuWechatV2_Server/wechat_app/views.py`这个文件

第11行

```
# 初始化 WeChat 类实例
wechat = WeChat(path="C:/Program Files/Tencent/WeChat/WeChat.exe", locale="zh-CN")

```
改成你安装微信的路径就行了，不过这样你需要自己编译Server了，或者源码运行

**Comment by biaolee** [comment]
/wechat/send_message/
发送消息 接口返回
System.Net.WebException:“操作超时”
服务器日志：
[21/Sep/2024 17:24:15] "GET /wechat/send_message/ HTTP/1.1" 405 35


/wechat/ping/
这个接口返回正常

**Comment by xieyumc** [comment]
你把微信路径改了吗，check_wechat_status返回什么呢

**Comment by biaolee** [comment]
> 你把微信路径改了吗，check_wechat_status返回什么呢

采用默认路径安装的
[21/Sep/2024 17:51:17] "POST /wechat/check_wechat_status HTTP/1.1" 301 0


之前有一次 返回：WeChat checked and prevent offline executed

**Comment by xieyumc** [comment]
返回WeChat checked and prevent offline executed说明是正常的，服务端已经检查到了微信在线

**Comment by xieyumc** [comment]
你是直接调用服务端的接口吗，有可能你发送的json格式不正确所以调用失败，你用客户端可以发送消息吗

**Comment by biaolee** [comment]
> 你是直接调用服务端的接口吗，有可能你发送的json格式不正确所以调用失败，你用客户端可以发送消息吗

$jsonData = '{"name": "文件传输助手", "text": "下班了吗？"}'
Invoke-WebRequest -Uri http://xxx:8000/wechat/send_message/ -Method Post -Headers @{"Content-Type"="application/json"} -Body $jsonData -ContentType "application/json; charset=utf-8"

这种方式 成功过。
但是 多试几次后 
响应 又变成301 或者405 了

**Comment by xieyumc** [comment]
嗯。。。既然这种方式成功过，说明服务端应该是没问题的，

我平时都是用客户端对服务端进行操作的，客户端没有这种情况，直接调用接口这个问题时有时无很难排查，暂时不打算修复

**Comment by xieyumc** [comment]
> 这个路径能改吗；重新安装怕聊天记录丢失。

已经增加服务端自定义微信安装路径的功能，欢迎更新最新版本

**Comment by anbinzhang** [comment]
收到，我试试

**Comment by Daydaylw3** [comment]
> > 这个路径能改吗；重新安装怕聊天记录丢失。
> 
> 已经增加服务端自定义微信安装路径的功能，欢迎更新最新版本

@xieyumc 请问下这个功能已经上线了是嘛，在 readme 里面好像没看到呢 0.0

**Comment by xieyumc** [comment]
> > > 这个路径能改吗；重新安装怕聊天记录丢失。
> > 
> > 
> > 已经增加服务端自定义微信安装路径的功能，欢迎更新最新版本
> 
> @xieyumc 请问下这个功能已经上线了是嘛，在 readme 里面好像没看到呢 0.0

<img width="874" alt="image" src="https://github.com/user-attachments/assets/71b1d10f-2252-4ed8-a252-d75b28a71f13">

看部署服务端这一节
