### ISSUE TITLE
exe运行和代码安装，都是如此，这是哪里的问题呢？

### ISSUE THREAD

**Issue by cheng0009** [xieyumc/YuYuWechat#15]
![image](https://github.com/user-attachments/assets/f7fc4d47-d54a-47d9-8d7c-e351cdefe7ae)

服务器端提示：
G:\YuYuWechat-2\YuYuWechat-2\YuYuWechatV2_Server>

G:\YuYuWechat-2\YuYuWechat-2\YuYuWechatV2_Server>python manage.py runserver 127.0.0.1:8000
Performing system checks...

System check identified no issues (0 silenced).
September 20, 2024 - 12:54:41
Django version 5.1.1, using settings 'YuYuWechatV2.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

[20/Sep/2024 12:54:48] "GET / HTTP/1.1" 404 179
[20/Sep/2024 12:54:48] "GET /favicon.ico HTTP/1.1" 404 179
[20/Sep/2024 12:54:52] "GET / HTTP/1.1" 404 179
[20/Sep/2024 12:54:52] "GET /favicon.ico HTTP/1.1" 404 179
[20/Sep/2024 12:55:01] "GET /wechat/ping HTTP/1.1" 301 0

http://127.0.0.1:8000/打开是如下提示：0.0.0.0也是。

Not Found
The requested resource was not found on this server.

**Comment by xieyumc** [comment]
我这边看你的YuYuWechatV2_Server已经启动成功了

YuYuWechatV2_Server只是提供接口，并没有管理界面，所以访问`http://127.0.0.1:8000`会报错

要管理，请安装YuYuWechatV2_Client

https://github.com/xieyumc/YuYuWechat?tab=readme-ov-file#yuyuwechatv2_client客户端


YuYuWechatV2_Server和YuYuWechatV2_Client是一套，不能单独分离

**Comment by Daydaylw3** [comment]
![image](https://github.com/user-attachments/assets/ee53d654-a190-4091-ad0b-b37ebcf7107c)

请问下，你这边不是说安装完 server 之后可以这样验证吗？

**Comment by xieyumc** [comment]
> ![image](https://github.com/user-attachments/assets/ee53d654-a190-4091-ad0b-b37ebcf7107c)
> 
> 
> 
> 请问下，你这边不是说安装完 server 之后可以这样验证吗？

是的，你遇到什么问题了吗，我建议新开一个issues
