### ISSUE TITLE
[BUG] "Failed to capture input parameters 这是什么问题

### ISSUE THREAD

**Issue by HanAsteroid** [xieyumc/YuYuWechat#19]
![image](https://github.com/user-attachments/assets/27b3a814-2597-4fe6-beb8-a2276993f5fc)

**Comment by xieyumc** [comment]
这个问题是因为我写的监控函数运行的装饰器，默认请求是json格式的
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/be2ce0a8-e04e-48a5-bf98-f96b45c8f298">

所以会出现捕获输入失败，算是一个bug，不过不影响运行，所以我就暂时没改hhh

**Comment by HanAsteroid** [comment]
但是只要出现这个错误，微信状态检测就失败了，提示连接不到服务器，同时定时任务也发送失败

**Comment by xieyumc** [comment]
<img width="553" alt="image" src="https://github.com/user-attachments/assets/2803c6d1-52cc-4139-9c4c-841f7fdaa3ce">

<img width="1000" alt="image" src="https://github.com/user-attachments/assets/8b6bee22-40a4-4689-ac4e-636971178c0b">


看函数运行结果是`成功`的，说明没有问题，我这边也有这个，微信状态检测正常的，应该不是这个问题

你的问题是程序已经正常运行了，微信状态检测也是正常，但是过一段时间后微信状态检测就会失败，是这样吗

**Comment by HanAsteroid** [comment]
是的，刚启动服务端时，微信状态检测是正常的，出一次错之后，再去看微信状态检测就失败了

**Comment by xieyumc** [comment]
YuYuWechat这边微信状态检测失败，那你win那边微信还是在线的吗

**Comment by HanAsteroid** [comment]
是的，微信还是在线的；我重启服务端，检测状态才能恢复正常

**Comment by xieyumc** [comment]
感谢你的回复，我需要更多信息来定位和调试问题：

你部署在什么平台，是docker部署还是源码呢？

你说重启服务端才能恢复正常，意思是客户端不需要重启，重启服务端就会恢复正常吗？那看起来问题出在服务端？

终端有没有错误信息呢，可以截图我看看

**Comment by HanAsteroid** [comment]
服务端是win，下载的exe直接部署的，客户端是docker；
我观察了终端，只有ping的日志，所以应该是客户端发起检测时，没有请求到服务端

**Comment by xieyumc** [comment]
🤔那么微信状态检测失败，服务器状态检测是成功的吗

另外除了微信状态检测失败，发送普通信息，发送定时消息的功能正常吗

**Comment by HanAsteroid** [comment]
是的，微信状态检测失败，服务器状态检测是成功；
发送定时消息失败，也没日志，感觉像是检测不到微信，直接没发了

**Comment by xieyumc** [comment]
一开始启动服务端，会有短暂的微信状态检测成功，那这段时间里可以发消息吗

**Comment by HanAsteroid** [comment]
我启动了三次服务端，只有一次短暂的发送成功了；
后来就是我最顶部截图这样，看到日志出错，然后微信状态就失败了

**Comment by xieyumc** [comment]
有点怪，这个问题我目前定位应该是服务端的问题

你可以试试换一台电脑，部署服务端吗

**Comment by HanAsteroid** [comment]
我明天有空再试试

**Comment by HanAsteroid** [comment]
![image](https://github.com/user-attachments/assets/ee6f931d-5ccc-425f-9e92-aca0eac92520)
![image](https://github.com/user-attachments/assets/93c576e4-614a-407f-af8b-3ed439710d2f)
<img width="744" alt="aa93fc8cba2b54ac497abb516c798c1" src="https://github.com/user-attachments/assets/54111baf-0b08-4817-a773-a6e309f58abe">
![image](https://github.com/user-attachments/assets/cdf3ef81-4bbc-46e8-a9f1-b4413dffa4be)
刚启动一切正常，发送一次消息就这样了

**Comment by xieyumc** [comment]
请留一下你的联系方式呢，我来看看

**Comment by HanAsteroid** [comment]
微信 476053729

**Comment by xieyumc** [comment]
问题已解决，因为没有视频输出，所以无法对微信进行操作，因为YuYuWechat就是依赖图形界面进行操作的，这个问题不属于bug，也无法解决

**Comment by HanAsteroid** [comment]
> 问题已解决，因为没有视频输出，所以无法对微信进行操作，因为YuYuWechat就是依赖图形界面进行操作的，这个问题不属于bug，也无法解决

感谢支持排查问题
