### ISSUE TITLE
[Feature] 通过HTTP Api 获取通讯录列表信息

### ISSUE THREAD

**Issue by rockjing** [xieyumc/YuYuWechat#20]
# 我想请求一个新功能🙏

**请求的功能**  
通过HTTP Api 获取通讯录列表信息

**实现思路？**  
我注意到实际代码上面是有获取通讯录功能，但是在HTTP api没有支持，是否考虑增加这个接口？

**Comment by xieyumc** [comment]
目前这个功能在客户端这边似乎很难找到一个应用场景，有什么建议吗？

如果单纯只是作为一个接口供调用的话，我增加这个功能的意向不是很大

你可以在服务端手动调用这个方法获得通讯录，或者手动给视图增加一个函数来实现

在没有明确的应用需求的情况下，我暂时不加这个功能
