### ISSUE TITLE
“[DEPLOYMENT ISSUE] “

### ISSUE THREAD

**Issue by bingbaicai** [xieyumc/YuYuWechat#22]
# 提出issues前请先确保你看完了部署文档

**描述问题**  
docker 部署后登录提示
CSRF verification failed. Request aborted.。

**日志和错误信息截图**  
![iShot_2024-10-15_07 30 57](https://github.com/user-attachments/assets/7a614bb4-fa7c-4c4f-bc8d-061165255e0b)
。

**环境 (请完成以下信息):**

	•	OS: 群辉7.2
	•	部署方式: Docker, 

**其他备注**

**Comment by bingbaicai** [comment]
现在部署好了，登录提示密码错误
admin
tykWyr-bepqu6-fafvym

**Comment by bingbaicai** [comment]
哈，明白了。
得先部署服务端，那么服务端能部署在docker上吗
文档里面没看到哦 谢谢

**Comment by xieyumc** [comment]
服务端需要图形化界面支持，所以还不支持docker
