### ISSUE TITLE
[BUG] 微信路径D盘无效

### ISSUE THREAD

**Issue by wulawula123123** [xieyumc/YuYuWechat#23]
# 提出issues前请先确保你看完了README

**描述Bug**  
微信路径放在D盘，显示微信不在线，换到默认路径就可以了，小白没有找到原因，还有一个问题就是，每次执行服务端bat文件，微信路径都会变成默认路径，是否可以单独做一个文件进行路径修改。

**重现步骤**  
请描述你做了什么操作

**截图**  
![微信图片_20241019132149](https://github.com/user-attachments/assets/f99fc2cd-fe70-4047-bc1e-929c78290e3c)
![微信图片_20241019132132](https://github.com/user-attachments/assets/63ef69fb-33e0-4a16-a1d3-a70e312ffa55)

**环境 (请完成以下信息):**
- OS: windows10
- 微信版本：3.9.12.17

**Comment by xieyumc** [comment]
感谢抓虫，这个问题，我需要更多时间调试和修复

**Comment by xieyumc** [comment]
我已经在文档里增加如何自定义微信路径的方法了，请访问：
https://github.com/xieyumc/YuYuWechat?tab=readme-ov-file#2-部署服务端
