### ISSUE TITLE
出现404 179

### ISSUE THREAD

**Issue by MRmingrui** [xieyumc/YuYuWechat#25]
![微信截图_20241031212745](https://github.com/user-attachments/assets/1e504eb1-30dc-43b7-af82-15d36bd6f329)
![微信截图_20241031212845](https://github.com/user-attachments/assets/bb5b905f-4084-4f15-9c45-c549ed1886c9)
按照教程搞了，但是还是出现这个情况

**Comment by xieyumc** [comment]
你访问什么链接报错404呢

**Comment by MRmingrui** [comment]
访问 127.0.0.1

**Comment by xieyumc** [comment]
你没安装客户端吧？服务端是没有首页的，你再仔细看看教程
