### ISSUE TITLE
[BUG] 微信路径设置失败?

### ISSUE THREAD

**Issue by hhuimie** [xieyumc/YuYuWechat#27]
# 提出issues前请先确保你看完了README

**描述Bug**  
按照readme中的方法, 设置微信路径, 但是客户端依旧显示不在线; 同时, 服务器如果重启之后, 微信路径会变成默认

**重现步骤**  
默认状态
![image](https://github.com/user-attachments/assets/bbb3ff59-278a-443b-a70b-01de373134cb)

修改路径为`C:/Program Files (x86)/Tencent/WeChat/WeChat.exe`, 并成功保存
![image](https://github.com/user-attachments/assets/c9357bba-4d11-45c0-b222-ac4d76d0148c)

此时刷新客户端, 显示不在线
![image](https://github.com/user-attachments/assets/3a848c9b-56a4-4905-adb2-daa6b4650b9f)

重启服务器, 路径恢复默认
![image](https://github.com/user-attachments/assets/b7bbe0c6-6a50-4f4e-8a32-a0b4dbb191f8)

**环境 (请完成以下信息):**
- OS: win10
- 微信版本: 3.9.12.17
- 其他: 不确定用了[防撤回补丁](https://github.com/huiyadanli/RevokeMsgPatcher), 并且开了两个微信有没有关系

**Comment by xieyumc** [comment]
嗯🤔...这个问题已经被其他人提出过了，我还需要更多时间调试

**Comment by hhuimie** [comment]
sorry, 看漏了人家的issue

**Comment by xieyumc** [comment]
我已经在文档里增加如何自定义微信路径的方法了，请访问：
https://github.com/xieyumc/YuYuWechat?tab=readme-ov-file#2-部署服务端
