### ISSUE TITLE
[BUG] 微信多开会导致检测失败或者找错微信

### ISSUE THREAD

**Issue by hhuimie** [xieyumc/YuYuWechat#28]
# 提出issues前请先确保你看完了README

**描述Bug**  
情况1: 用了[防撤回补丁](https://github.com/huiyadanli/RevokeMsgPatcher)中的多开功能, 微信状态检测失败, 每次检测都会打开一个新的微信登录窗口

情况2: 卸载[防撤回补丁](https://github.com/huiyadanli/RevokeMsgPatcher), 直接用手速, 或者一个简单的批处理多开微信, 状态检测成功, 但是每次检测的时候, 打开的微信都是上次打开过的, 如果我手动打开另一个微信窗口B, 那么检测的时候就是微信B
```
@echo off
start C:\"Program Files (x86)"\Tencent\WeChat\WeChat.exe
start C:\"Program Files (x86)"\Tencent\WeChat\WeChat.exe
exit
```

**环境 (请完成以下信息):**
- OS: win10
- 微信版本: 3.9.12.17

**Comment by xieyumc** [comment]
本程序确实没有处理多开微信的情况，本程序只会从默认路径打开微信，然后进行操作

如果你想多开，我感觉可以把不同微信安装在不同位置，然后多开本程序，指定不同路径微信

**Comment by hhuimie** [comment]
可否考虑用快捷键的方式去区分两个微信, 用户指定快捷键打开对应微信

**Comment by xieyumc** [comment]
这个功能还是很小众的需求，我不打算在main分支里实现，如果你有需要，可以自己fork本程序后自行修改
