### ISSUE TITLE
[BUG] 微信会把人踢下线

### ISSUE THREAD

**Issue by Daydaylw3** [xieyumc/YuYuWechat#29]
# 提出issues前请先确保你看完了README

> 已看完，并且扫了所有 issue 没发现有人提到

**描述Bug**  

调用 api 报错：`{"status": "error", "error": "Find Control Timeout(10s): {Depth: 8, Name: 'Xxxx', ControlType: EditControl}"}`，然后查看 server 端发现微信被踢下线了，需要重新登陆

**重现步骤**  

调用查看微信聊天记录：

```shell
POST /wechat/get_dialogs/ HTTP/1.1
Host: 192.168.31.171:8000
Content-Type: application/json
User-Agent: PostmanRuntime/7.42.0
Accept: */*
Postman-Token: 79e326c4-6cc0-4ba8-aa47-61a594121371
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 33
 
{"name": "Xxx", "n_msg": 5}

HTTP/1.1 500 Internal Server Error
Date: Sat, 23 Nov 2024 03:12:27 GMT
Server: WSGIServer/0.2 CPython/3.11.9
Content-Type: application/json
Content-Length: 117
Vary: origin
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin
Cross-Origin-Opener-Policy: same-origin
 
{"status": "error", "error": "Find Control Timeout(10s): {Depth: 8, Name: '\u641c\u7d22', ControlType: EditControl}"}
```

**环境 (请完成以下信息):**
- OS：windows11
- 微信版本：3.9.12.17

**Comment by xieyumc** [comment]
那你重新登录一下微信就行了，这个问题通常出现在微信登录在一个新设备上时，微信会不定时下线

YuYuWechat是使用图形化界面进行自动化操作，不涉及破解/破坏微信的任何代码，理论上是不会遭到微信风控的

我自己的微信挂了一个月了，都没什么问题

**Comment by Daydaylw3** [comment]
> 那你重新登录一下微信就行了，这个问题通常出现在微信登录在一个新设备上时，微信会不定时下线
> 
> YuYuWechat是使用图形化界面进行自动化操作，不涉及破解/破坏微信的任何代码，理论上是不会遭到微信风控的
> 
> 我自己的微信挂了一个月了，都没什么问题

那我再观察观察一星期看看哈

**Comment by Daydaylw3** [comment]
> 那你重新登录一下微信就行了，这个问题通常出现在微信登录在一个新设备上时，微信会不定时下线
> 
> YuYuWechat是使用图形化界面进行自动化操作，不涉及破解/破坏微信的任何代码，理论上是不会遭到微信风控的
> 
> 我自己的微信挂了一个月了，都没什么问题

看上去确实是的，新的电脑，过段时间会 T 下线，但是多登录几天就好了
