### ISSUE TITLE
关于@功能

### ISSUE THREAD

**Issue by moonmakeup** [xieyumc/YuYuWechat#31]
源码里面实现了，但是看着好像没有对应接口调用？是我没找到还是有其它原因导致没放出来。

**Comment by xieyumc** [comment]
是的，我还没想好这个该如何在图形化界面方便的定义和调用，所以就没有实现，你有思路的话可以试试

**Comment by moonmakeup** [comment]
> 是的，我还没想好这个该如何在图形化界面方便的定义和调用，所以就没有实现，你有思路的话可以试试

了解了
