### ISSUE TITLE
我拉取镜像后打不开前端

### ISSUE THREAD

**Issue by baiyuqian** [xieyumc/YuYuWechat#33]
我打不开前端

![926e8ed1af1ebe062fd563e560983b0](https://github.com/user-attachments/assets/f37a1c72-10d1-4d19-8e52-2f804dcb8c0f)

![2a0cb155d444329ba20ad648de92ffa](https://github.com/user-attachments/assets/c1766d75-4f57-44a2-8f37-842e6c4227d8)

![1c422944a6e2b8241f3ba2450cfd65d](https://github.com/user-attachments/assets/f8ab4f30-8a2b-4d89-9ddf-99f01f901bde)

**其他备注**
我已经拉取镜像，可打不开前端，是我的拉取镜像有问题吗

**Comment by baiyuqian** [comment]
为什么我打不开前端 清晰简洁地描述在部署过程中遇到的问题。

 ![926e8ed1af1ebe062fd563e560983b0](https://private-user-images.githubusercontent.com/191705280/395807930-f37a1c72-10d1-4d19-8e52-2f804dcb8c0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxOTgzMjcsIm5iZiI6MTczNDE5ODAyNywicGF0aCI6Ii8xOTE3MDUyODAvMzk1ODA3OTMwLWYzN2ExYzcyLTEwZDEtNGQxOS04ZTUyLTJmODA0ZGNiOGMwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNFQxNzQwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NGViNThjODQzNTA1MWMyMTc1ZmE0YmM5YWE5ZDQwNDVmZDI2OGRlOWNhNDE0Yjg1ZmRjYTcxZGY4MTQ4OTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.udf8VnQ8-yfXlRVHG0ZxU3CDLg9RZJ3s57pRAkOeu24)
> 
> ![2a0cb155d444329ba20ad648de92ffa](https://private-user-images.githubusercontent.com/191705280/395807935-c1766d75-4f57-44a2-8f37-842e6c4227d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxOTgzMjcsIm5iZiI6MTczNDE5ODAyNywicGF0aCI6Ii8xOTE3MDUyODAvMzk1ODA3OTM1LWMxNzY2ZDc1LTRmNTctNDRhMi04ZjM3LTg0MmU2YzQyMjdkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNFQxNzQwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTM0MTNlZjQwYWZkY2E5MWU3NzU0MGI5MzJkZTQxY2RjNjExYjRmNDZlMjU1ODM0NGNjMTFjOWJiZTA3YTE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5WEBJ9kby2as-JA92Fn2LcY4Hp2IHOXAKsh4UUTD7kg)
> 
> ![1c422944a6e2b8241f3ba2450cfd65d](https://private-user-images.githubusercontent.com/191705280/395808032-f8ab4f30-8a2b-4d89-9ddf-99f01f901bde.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxOTgzMjcsIm5iZiI6MTczNDE5ODAyNywicGF0aCI6Ii8xOTE3MDUyODAvMzk1ODA4MDMyLWY4YWI0ZjMwLThhMmItNGQ4OS05ZGRmLTk5ZjAxZjkwMWJkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNFQxNzQwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjI4YTQwNDM0Y2ExMGU3NGJiMDUxZDM3MzYzYTQ3ZDlkYWFkZjMwM2FmZWY0NWZiZGIzMGM5YTA0MDgzMDE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cLwatwTE6vtl-AUzYhWMKF39VE7SMbQFg8_dvhoXMRU)
> 
我已经拉取镜像，可打不开前端，是我的拉取镜像有问题吗

**Comment by baiyuqian** [comment]
> **描述问题** 为什么我打不开前端 
> **日志和错误信息截图**  ![926e8ed1af1ebe062fd563e560983b0](https://private-user-images.githubusercontent.com/191705280/395807930-f37a1c72-10d1-4d19-8e52-2f804dcb8c0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxOTgzODAsIm5iZiI6MTczNDE5ODA4MCwicGF0aCI6Ii8xOTE3MDUyODAvMzk1ODA3OTMwLWYzN2ExYzcyLTEwZDEtNGQxOS04ZTUyLTJmODA0ZGNiOGMwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNFQxNzQxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjkzNGMwYTZmN2IyNmE1MGVmNGU2MGUyZTUyY2U3NWJjNmY2NzdhY2JhYTlhNzJkOWQwMzZiZjFkYjcyNzY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YQ9zVbIjD1sOB3VbnqH541AuDXXl0yjg2MQPejx8U1g)
> 
> ![2a0cb155d444329ba20ad648de92ffa](https://private-user-images.githubusercontent.com/191705280/395807935-c1766d75-4f57-44a2-8f37-842e6c4227d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxOTgzODAsIm5iZiI6MTczNDE5ODA4MCwicGF0aCI6Ii8xOTE3MDUyODAvMzk1ODA3OTM1LWMxNzY2ZDc1LTRmNTctNDRhMi04ZjM3LTg0MmU2YzQyMjdkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNFQxNzQxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NGMwNThjMWUyNDQ5MTBlNTkyZjkzNWIzMWRjMDU1Y2RmZWY2YTIwZmY0MDJiY2VhN2ZmNTY4MTU4NThkOGJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WehdNzpcvJV6dlL_9X37b0kw_L7Tb8rFAIxw-eHJw-w)
> 
> ![1c422944a6e2b8241f3ba2450cfd65d](https://private-user-images.githubusercontent.com/191705280/395808032-f8ab4f30-8a2b-4d89-9ddf-99f01f901bde.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxOTgzODAsIm5iZiI6MTczNDE5ODA4MCwicGF0aCI6Ii8xOTE3MDUyODAvMzk1ODA4MDMyLWY4YWI0ZjMwLThhMmItNGQ4OS05ZGRmLTk5ZjAxZjkwMWJkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNFQxNzQxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWNlN2EzZTkxNWNmNjY2MmMyOWMwYTgzNGY5YjQwNjEzMzNmMTZkN2Y1M2YwNzE4MGI3ZjhkNzBkNDU5OTk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jB0nnr9AD3OfgYTKQOR2D2su0-p9FLpLAESCvSy2zDw)
> 

> **其他备注** 我已经拉取镜像，可打不开前端，是我的拉取镜像有问题吗

**Comment by baiyuqian** [comment]
![image](https://github.com/user-attachments/assets/bfa00277-f645-4a39-a627-511a8cf33e22)
我没运行.....

**Comment by baiyuqian** [comment]
![image](https://github.com/user-attachments/assets/39035dc3-023f-461d-835f-c72a8466e68d)
连接的服务器是我自己买的云服务器吗？

**Comment by xieyumc** [comment]
指的是yuyuwechat服务端，安装了微信那个

**Comment by baiyuqian** [comment]
> Reference

我不懂的是我填写连接服务器是指的哪个ip

**Comment by xieyumc** [comment]
> > Reference
> 
> 我不懂的是我填写连接服务器是指的哪个ip

我认为readme已经写的够清楚了，请先通读readme，然后再对不懂的地方提问

请注意，我并没有义务教你如何使用本项目，请你保持基本的礼貌和尊重

**Comment by baiyuqian** [comment]
> > > 参考
> > 
> > 
> > 我不懂的是我填写连接服务器是指的哪个ip
> 
> 我认为readme已经写的够清楚了，请先通读readme，然后再对不懂的地方提问
> 
> 请注意，我并没有义务教你如何使用本项目，请你保持基本的礼貌和尊重

非常抱歉我的不礼貌行为，可能没有直接表达到位，我是在尝试了
但是没法连接，可能是端口不对，也可能我的ip查询有问题。我有些怀疑本身是不是要单独放在云服务器上，而不是放在本地。

**Comment by xieyumc** [comment]
你部署了服务端吗

**Comment by baiyuqian** [comment]
> 你部署了服务端吗

原来这个是我服务端在该cmd上，我当时问了几个大学学习内容偏后端的朋友，我们都没搞明白，为什么一直ping不通，但是没人注意到服务端和其他的一些临时cmd窗口一起被关闭了，非常感谢。
