### ISSUE TITLE
自动循环发那个功能用不了。但是单次发送的功能能用

### ISSUE THREAD

**Issue by Jack123456chen** [xieyumc/YuYuWechat#4]
自动循环发那个功能用不了，后台显示”TypeError: the first argument must be callable“，前台就只是显示一个error

但是同样的条件单次发送的功能能用。

**Comment by xieyumc** [comment]
能把完整的控制台命令贴一下吗

**Comment by LnightSama** [comment]
我也是一样，控制台是这样报错的
![PixPin_2024-07-05_19-56-17](https://github.com/xieyumc/YuYuWechat/assets/65227018/ef6cc7a1-7ebf-438f-b061-8e8f094aa7ea)

**Comment by xieyumc** [comment]
好的收到报错了，我再看看 @LnightSama

**Comment by xieyumc** [comment]
重构了代码，已解决循环发送问题
