### ISSUE TITLE
单独发送失败，定时一直报错，附图片！

### ISSUE THREAD

**Issue by TerryZT** [xieyumc/YuYuWechat#5]
![1717566217376](https://github.com/xieyumc/YuYuWechat/assets/89681010/eb488f9e-6547-4f7d-9f7e-b90f9fecf481)
单独发送报错图片，
定时自动发送一直未设置运行，一直显示报错。
定时发送的时间，例如 9:00，在表格中怎么设置？如果同样的内容一天发送两次， 早上 9:00 一次，下午 5:00 一次，如何设置？

**Comment by TerryZT** [comment]
是发可以定时发送到微信群里？上面设置的是群消息发送

**Comment by xieyumc** [comment]
感谢使用：

**定期发送**
<img width="362" alt="image" src="https://github.com/xieyumc/YuYuWechat/assets/47858007/a48fc2ac-fef9-4d41-9898-15e4cd9e7ff9">

我这里看到你添加日期列没填，这样会导致定期发送失败，因为定期自动发送功能是用发送时间列+添加时间列来实现的。

**单独发送**
看这个output报错，应该是没找到微信按钮，也有可能是微信群的问题，你试试发送给好友可以吗？按理说，是可以发送给微信群的

另外，能把控制台的输出和excel表格内容发一下吗，这样我能更清晰定位问题

**Comment by TerryZT** [comment]
![1717568611008](https://github.com/xieyumc/YuYuWechat/assets/89681010/3a91d2e4-9103-4706-be3e-a28d6b587130)
![1717569075812](https://github.com/xieyumc/YuYuWechat/assets/89681010/86f5aecf-c72a-4923-85ac-df90699a341e)
按照说明设置的表格内容，如果表格有批量内容，在时间的位置设定好了是全部按照这个执行吗？
[自然拼读 1-5 级别群打卡内容-f47ce0b54257.xlsx](https://github.com/user-attachments/files/15574186/1-5.-f47ce0b54257.xlsx)
不知道是不是我操作有问题？
建议一下，路径最好可以点击以后选择文件所在的位置，我直接复制的时候路径不全，在图标点击属性选择才对

**Comment by TerryZT** [comment]
自动发送时间可以在表格直接在两列上写上不同时间，前面是日期，例如: 2024-06-05  8:00  17:00，这样两个时间可以执行发送吗？这样设置三列，日期，时间，时间

**Comment by xieyumc** [comment]
感谢回复：

_**能否把控制台的报错贴一下呢，就是那个黑黑的小窗口**_

> 自动发送时间可以在表格直接在两列上写上不同时间，前面是日期，例如: 2024-06-05 8:00 17:00，这样两个时间可以执行发送吗？这样设置三列，日期，时间，时间

你的建议很好，我已经计划添加多时间功能了，目前yuyuwechat还只能在一天内规定的时间单次发送


> 按照说明设置的表格内容，如果表格有批量内容，在时间的位置设定好了是全部按照这个执行吗？

定时自动发送消息的逻辑为：
程序在后台一直检测时间，时间到了，如14:25，则从表格中筛选日期（在你的例子里是C
列）为今天的消息，发送给对象，然后再把C列加上D列的时间。

我下载了你的excel看了一下，有几个问题：

1.D列是空的，在这一列，你需要加上时间增量，如0-0-1，则是表示每次发送消息后，给发送日期加一天，这样做就是日循环发送消息

2.C列格式不是时间

3.表格最上面一行不需要有内容
<img width="666" alt="image" src="https://github.com/xieyumc/YuYuWechat/assets/47858007/e66a9e7b-f758-44a1-8811-cc22e3625bfc">


我尝试修改了一下你的excel，在这个文件里，因为今天是6月5号，会发送第1-9条消息给“阅陶测试”，并且给C
列加上1天的时间增量
[Copy of 1-5.-f47ce0b54257.xlsx](https://github.com/user-attachments/files/15574566/Copy.of.1-5.-f47ce0b54257.xlsx)

> 建议一下，路径最好可以点击以后选择文件所在的位置，我直接复制的时候路径不全，在图标点击属性选择才对

感谢建议，这个功能我考虑过，但gradio有文件路径匿名功能，如果选择文件会让程序无法读取路径，所以只能手动填写路径

你可以试试使用我发的excel文件，选择“发送一次消息”，看看能不能正常运行，如果有问题欢迎再提出👏

**Comment by TerryZT** [comment]
![WechatIMG33](https://github.com/xieyumc/YuYuWechat/assets/89681010/ae9b3fed-f7df-4716-9e81-e18f1823b56c)
![WechatIMG34](https://github.com/xieyumc/YuYuWechat/assets/89681010/3012bbac-6ce5-47f7-b893-9e293f6d452a)
因为我需要自动通过好友，欢迎语，所以使用了其他的 bot，然后在使用你的这个功能，部署存在py版本不一致，那个bot是 3.12，你这个最高是 3.11，所以我用exe执行的，不知道是否有影响。我先贴图出来，然后我去试一下你改过的文档，个人建议，你的模板表格和程序放在一起，下载的人直接用你的表格，只改内容会好点，这样错误的几率会降低，按照文字我已经是反复核对，最后还是有问题。

**Comment by xieyumc** [comment]
感谢建议：
1.exe已经打包好所有python环境和包了，应该不存在py版本不一致的问题。如果需要不同版本的py环境，可以考虑使用conda部署

再次感谢你的建议，模版文件我稍后会更新，我修改后的excel文件是否可以正常工作呢

**Comment by TerryZT** [comment]
![WechatIMG38](https://github.com/xieyumc/YuYuWechat/assets/89681010/8e87c1f3-a7e4-4b38-8b6c-d0f947e0eb75)
![WechatIMG40](https://github.com/xieyumc/YuYuWechat/assets/89681010/74601eca-560f-402a-96a9-6365bb701c4b)
关闭了另外一个bot，只执行了这个一个程序还是报错。

**Comment by xieyumc** [comment]
<img width="1489" alt="image" src="https://github.com/xieyumc/YuYuWechat/assets/47858007/4ec448b9-06ef-434d-8b4b-aaae375acdfa">
我这边测试了一下，可以正常运行呢，你方便留一下微信吗

**Comment by TerryZT** [comment]
terryzou92324

**Comment by xieyumc** [comment]
微信版本过低，已解决
