### ISSUE TITLE
单纯好奇

### ISSUE THREAD

**Issue by yanishuang** [xieyumc/YuYuWechat#6]
好奇这个功能，除了定时功能之外，和微信自带的群发工具有啥区别

**Comment by xieyumc** [comment]
微信群发只能一条消息发给多个人吧，我是为了给不同人发不同消息才开发这个工具的🤔

**Comment by yanishuang** [comment]
不同人发不同消息，不就是本身微信的功能吗？单聊。不过作为管理工具挺好的，
