### ISSUE TITLE
无法使用发送消息功能，显示未找到指定文件

### ISSUE THREAD

**Issue by Lzyj07** [xieyumc/YuYuWechat#8]
问题描述：明明已经找到了excel文件，并且读取出来，但是显示找不到指定文件。
系统 win10
wechat  3.9.11.17
```
output：
发送给25个好友

发送给: xxx   信息: 项目编号：....... 

发送信息失败

 [WinError 2] 系统找不到指定的文件。

```
![image](https://github.com/user-attachments/assets/7f3a6481-335d-48ab-bdd7-197bdf5a0d92)

**Comment by Lzyj07** [comment]
找到问题了，原来是wechat路径输错了 。。。打扰了

**Comment by Daydaylw3** [comment]
@Lzyj07 @xieyumc hi，我也遇到这个问题，我微信安装目录为 `C:\Program Files\Tencent\Weixin`，这样是对的吗？
