### ISSUE TITLE
请问一下这是什么原因

### ISSUE THREAD

**Issue by 2924547961** [xieyumc/YuYuWechat#9]
Performing system checks...

System check identified no issues (0 silenced).
July 23, 2024 - 09:06:43
Django version 5.0.7, using settings 'YuYuWechatV2.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.

[23/Jul/2024 09:07:24] "GET /wechat/ping HTTP/1.1" 301 0

**Comment by xieyumc** [comment]
🤔我没有发现问题，请给出详细的问题描述

你在浏览器输入`http://127.0.0.1:8000/wechat/ping/`会收到`pong`吗

**Comment by icxw** [comment]
> 🤔我没有发现问题，请给出详细的问题描述
> 
> 你在浏览器输入`http://127.0.0.1:8000/wechat/ping/`会收到`pong`吗
你好我也是这样，，能收到

{
    "status": "pong"
}

但是

主页打开是这个


Not Found
The requested resource was not found on this server.

**Comment by xieyumc** [comment]
> > 🤔我没有发现问题，请给出详细的问题描述
> > 你在浏览器输入`http://127.0.0.1:8000/wechat/ping/`会收到`pong`吗
> > 你好我也是这样，，能收到
> 
> { "status": "pong" }
> 
> 但是
> 
> 主页打开是这个
> 
> Not Found The requested resource was not found on this server.

你没有安装客户端

**Comment by icxw** [comment]
> 🤔我没有发现问题，请给出详细的问题描述
> 
> 你在浏览器输入`http://127.0.0.1:8000/wechat/ping/`会收到`pong`吗
你好我也是这样，，能收到

{
    "status": "pong"
}

但是

主页打开是这个


Not Found
The requested resource was not found on this server.

**Comment by icxw** [comment]
> > > 🤔我没有发现问题，请给出详细的问题描述
> > > 你在浏览器输入`http://127.0.0.1:8000/wechat/ping/`会收到`pong`吗
> > > 你好我也是这样，，能收到
> > 
> > 
> > { "status": "pong" }
> > 但是
> > 主页打开是这个
> > Not Found The requested resource was not found on this server.
> 
> 你没有安装客户端

请问如何安装呢。。我看网上都没教程。。。我用的是EXE的....

**Comment by xieyumc** [comment]
> > > > 🤔我没有发现问题，请给出详细的问题描述
> > > > 你在浏览器输入`http://127.0.0.1:8000/wechat/ping/`会收到`pong`吗
> > > > 你好我也是这样，，能收到
> > > 
> > > 
> > > { "status": "pong" }
> > > 但是
> > > 主页打开是这个
> > > Not Found The requested resource was not found on this server.
> > 
> > 
> > 你没有安装客户端
> 
> 请问如何安装呢。。我看网上都没教程。。。我用的是EXE的....

看readme的
3. 部署客户端
